# Generated by Django 6.0.5 on 2026-06-10 04:41

import store.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product.product_image_path),
        ),
    ]
